name: CustomShopUI
main: AlexPads\ShopUI\TinyPixelDevz\Shop
version: 3.0.2
api: [3.3.2]
author: TinyPixelDevz
website: saltypixel.ga
depend:
- EconomyAPI
commands:
  shop:
    description: "Opens Shop Menu... By: SaltyPixelDevz!"