name: CustomShopUI
main: AlexPads\ShopUI\SaltyPixelDevz\Shop
version: 3.2.0
api: [3.3.2]
author: TinyPixelDevz
website: saltypixel.ga
depend:
- EconomyAPI
commands:
  shop:
    description: "Opens ShopUI Menu... By: SaltyPixelDevz!"