name: CustomShopUI
main: AlexPads\ShopUI\SaltyPixelDevz\Shop
version: 3.2.1
api: [3.0.0]
author: TinyPixelDevz
website: saltypixel.ga
depend:
- EconomyAPI
commands:
  shop:
    description: "Opens ShopUI Menu... By: SaltyPixelDevz!"
