name: CustomShopUI
main: AlexPads\ShopUI\SaltyPixelDevz\Shop
version: 3.5.0
api: [3.0.0]
author: SaltyPixelDevz
website: http://saltypixel.ga
depend:
- EconomyAPI
commands:
  shop:
    description: "Opens CustomShopUI"