name: CustomShopUI
main: AlexPads\ShopUI\TinyPixelDevz\Shop
version: 2.0.0
api: [3.0.0]
author: TinyPixelDevz
website: tinypixel.ga
commands:
 shop:
  description: "Opens server selection Menu... By: TinyPixelDevz!"
