name: CustomShopUIv2
main: SaltyPixelDevz\CustomShopUIv2\gui
version: 4.0.0
api: 3.0.0
author: SaltyPixelDevz
description: "Shop GUI Plugin that Aim for the Most Stable and Reliable Updates!"
website: http://saltypixel.ga
commands:
 shop:
  description: "ShopGUI Plugin by the SaltyPixelDevz!"