name: CustomShopUI
main: AlexPads\ShopUI\TinyPixelDevz\Shop
version: 2.0.7
depend:
  FormAPI: https://poggit.pmmp.io/get/FormAPI
api: [3.0.0]
author: TinyPixelDevz
website: saltypixel.ga
commands:
 shop:
  description: "Opens Shop Menu... By: SaltyPixelDevz!"
