name: CustomShopUI
main: SaltyPixelDevz\CustomShopUIv2\Shop
version: 3.5.3
api: [3.0.0]
author: SaltyPixelDevz
website: http://saltypixel.ga
depend:
- EconomyAPI
commands:
  shop:
    description: "Opens CustomShopUI"