Title: §4Shop§eUI
Food: Food
Enabled: true
IP: TinyPixel.us.to
Port: 19132
Message: §aYou are being Moved!
Server-1: §a§lHub
Server-2: §b§lSkyBlock
Server-3: §e§lSurvival
Server-4: §44th server
Server-5: §55th server
Server-6:
Server-7:
Server-8:
Server-9:
Server-10:
IP1: TinyPixel.us.to
IP2: TinySkyBlock.us.to
IP3: TinySurvival.us.to
IP4: iphere.yeet
IP5: iphere.yeet2
IP6:
IP7:
IP8:
IP9:
IP10:
Port1: 19132
Port2: 19132
Port3: 19132
Port4: 58757
Port5: 97035
Port6:
Port7:
Port8:
Port9:
Port10:
Servers: 1
broadcast: §awas Moved to
Color: §e
Prefix: §l§aTiny§4Pixel§6»»