## Offical TinyPixel Shop!
## Food items/ids
## is the Price of Steak
Food1-Price: 250
## is the Item ID of Steak
## This Id Is Changeable BUT Dont change the SteakID part just the ID
Food1ID: 364
## is the ammount of Steak
Food1Num: 32
## is the Meta or the second number Ex.. 364, 0, 32 has NO damage. (useful for tools), OR, 364, 1, 32 is Steak with the id 364:1
Food1Met: 0

## Blocks items/ids

## Tools/Farming items/ids

## Armor

## Raiding items/ids
